name: Linux_Container_Workflow

#このアクションがいつ実行されるか
#リポジトリ内の変更が検出されたときに自動的にトリガー
on: [push]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        #Azureへログイン
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        #コンテナイメージのビルド＆プッシュ
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}

        #コンテナーAppsのデプロイ
        - name: Build and deploy Container App
          uses: azure/container-apps-deploy-action@v1
          with:
            acrName: ${{ secrets.REGISTORY_NAME }}
            containerAppName: ${{ secrets.CONTAINER_APPS_NAME }}
            resourceGroup: ${{ secrets.RESOURCE_GROUP }}
            imageToDeploy: ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}

